name    'curator-hyperic'
version '1.0.4'
source 'git://github.com/gettyimages/puppet-hyperic'
author 'preston.norvell@gettyimages.com'
license 'MIT'
summary 'vFabric Hyperic Module'
description 'vFabric Hyperic Module'
project_page 'https://github.com/gettyimages/puppet-hyperic'
