name    'getty-hyperic'
version '1.0.0'
source 'git://github.com/curator/puppet-hyperic'
author 'GettyImages'
license 'MIT'
summary 'vFabric Hyperic Module'
description 'vFabric Hyperic Module'
project_page 'https://github.com/curator/puppet-hyperic'
