name    'getty-hyperic'
version '1.0.2'
source 'git://github.com/curator/puppet-hyperic'
author 'preston.norvell@gettyimages.com'
license 'MIT'
summary 'vFabric Hyperic Module'
description 'vFabric Hyperic Module'
project_page 'https://github.com/curator/puppet-hyperic'
